### ISSUE TITLE
ResourceFilename destroyed

### ISSUE THREAD

**Issue by maansson** [XSARUS/inriver-bynder#4]
When importing new Assets from Bynder the filename is destroyed. 
```
resourceEntity.GetField(FieldTypeId.ResourceFileName).Data = $"{bynderAssetId}_{asset.GetOriginalFileName()}";
```
What is the reason for prefixing the filename with the AssetId?

**Comment by bram-xsarus** [comment]
> What is the reason for prefixing the filename with the AssetId?

We have done this to ensure no files currently in inRiver will be overwritten by the connector.
Depending on your setup you might not want that, perhaps we should make it configurable.

**Comment by bram-xsarus** [comment]
It is currently already possible. You can create a capture group in the regular expression called ResourceFileName.

**Comment by maansson** [comment]
Something like this perhaps `^(?<ResourceFilename>.*)`?

**Comment by bram-xsarus** [comment]
Didn't test it, but yes that might work. With this regex you don't map other fields of the filename to inRiver.
We have an example running:

`(?<ResourceFilename>^(?<VariantName>[0-9]+_[a-zA-Z]+)_(?<ResourceImageType>[a-zA-Z]+)_(?<ResourcePriority>[0-9]+).+)
`
Using the VariantName it will create links, and the other fields are set on the Resource.
Luckily you can nest matching groups....

**Comment by maansson** [comment]
Thanks, that was my next question. Doing that however also gives an empty Full match, with an empty GroupName. I guess I can live with that. 
`(?<ResourceFilename>^(?<ItemArticleNumber>[A-Z0-9]+).+)`
![image](https://user-images.githubusercontent.com/10449396/59334185-35923e00-8cfa-11e9-9e5b-a9da69f4b86f.png)
